eval()评估函数，用来去掉参数最外侧引号

In [6]:
#TempCpnvert,py
TempStr = input("请输入带有符号的温度值：")
if TempStr[-1] in ['F','f']:
    C=(eval(TempStr[0:-1]) - 32)/1.8
    print("转换后为{:.2f}C".format(C))
elif TempStr[-1] in['C','c']:
    F = 1.8*eval(TempStr[0:-1]) + 32
    print("转换后为{:.2f}F".format(F))
else:
    print("输入格式错误")    

请输入带有符号的温度值：23
输入格式错误


In [ ]:
#TempCpnvert,py
TempStr = input()
if TempStr[0] in ['F','f']:
    C=(eval(TempStr[1:]) - 32)/1.8
    print("C{:.2f}".format(C))
elif TempStr[0] in['C','c']:
    F = 1.8*eval(TempStr[1:]) + 32
    print("F{:.2f}".format(F))
else:
    print("输入格式错误")     

In [ ]:
a=input()
if a[1] in ['R','M','B']:
    U=a[3:]/6.78
    print("USD{:.2f}".format(U))
elif a[1] in ['U','S','D']
    R=a[3:]*6.78
    print({:.2f}.format(R))

In [ ]:
CurStr = input()
if CurStr[:3] == "RMB":
    print("USD{:.2f}".format(eval(CurStr[3:])/6.78))
elif CurStr[:3] in ['USD']:
    print("RMB{:.2f}".format(eval(CurStr[3:])*6.78))

# Numpy 

## Numpy是Python的一种开源的数值计算扩展，其提供了许多高级的数值编程工具，一个重要特性是他的数组计算

###  导入python库使用关键字import，后面可以自定义库的简称，但是一般将Numpy命名为np，pandas命名为pd

#### 使用前一定要先导入Numpy包，导入的方法有：

In [3]:
import numpy

In [1]:
import numpy as np

In [4]:
from numpy import *

In [2]:
import numpy as np
dt = np.dtype(np.int32)
print(dt)
print(type(dt))

int32
<class 'numpy.dtype[int32]'>


In [3]:
import numpy as np
student = np.dtype([("name","S20"),("age",'<20' )])
print(student)

TypeError: data type '' not understood

# 1.Numpy 的数组对象及其索引

### 数组上的数学参数

### array()函数

       原型：numpy.array(object,dtype = None,copy = True, order = None, subok = False, ndmin = 0)
         object指数组或嵌套的序列
         dtype指数组元素的数据类型
         copy对象是否需要复制
        order创建数组的样式，C为行方向，F为列方向，A为任意方向（默认）
        subok默认返回一个与基类类型一致的数组
        ndmin制定生成数组的最小纬度

In [4]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(type(arr))

[1 2 3 4 5]
int64
<class 'numpy.ndarray'>


In [26]:
#一维数组，元素类型要一致
import numpy as np
arr = np.array([1,2,3,4.5,5])
print(arr)
print(arr.dtype)
print(type(arr))

[1.  2.  3.  4.5 5. ]
float64
<class 'numpy.ndarray'>


In [40]:
#多维数组
arr2 = np.array([[1,2,3,],[1,2,3.5]])
arr2

array([[1. , 2. , 3. ],
       [1. , 2. , 3.5]])

In [58]:
#结构化数据类型
student = np.dtype([("name", "S2"),("age", "i4")])
arr=np.array([("sunck", 18)],dtype=student)

### asarray函数

#### numpy.asarray(a,dtype = None, order = None)

#### 假象我们将列表中的每个元素增加1，但列表不支持这样的操作

### empty 函数

#### numpy.empty(shape,dtype=float,order='c') 作用为创建一个指定形状、数据类型且未初始化的数组
shape 数组形状
dtype 数据类型
order同上

In [45]:
arr = np.empty([3,2],dtype=int)
arr

array([[-1447909200,         369],
       [          0,           0],
       [          1,     5242957]])

### zeros函数   

#### numpy.empty(shape,dtype=float,order='c') 创建制定大小的数组，数组元素以0来填充

In [57]:
arr = np.zeros([2,2],dtype=[('name','i2'),('y','f')])
arr

array([[(0, 0.), (0, 0.)],
       [(0, 0.), (0, 0.)]], dtype=[('name', '<i2'), ('y', '<f4')])

In [ ]:
a=[1,2,3,4,5,6]
a

In [ ]:
 [x+1 for x in a]

In [13]:
b=[2,3,4,5,6]
a+b

[1, 2, 3, 4, 2, 3, 4, 5, 6]

In [17]:
[x+y for(x,y)in zip(a,b)]

[3, 5, 7, 9, 11]

使用np函数可以简化步骤

In [21]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [22]:
a+1

array([2, 3, 4, 5])

In [23]:
a*2

array([2, 4, 6, 8])

In [24]:
b=np.array([2,3,4,5])

In [25]:
a*b

array([ 2,  6, 12, 20])

### 产生数组

#### 从列表中产生数组

In [27]:
l=[0,1,2,3]
a=np.array(l)
a

array([0, 1, 2, 3])

#### 从列表传入：

In [29]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

#### 生成全0数组

In [30]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

#### 生成全1的 整数 数组

In [33]:
np.ones(5,dtype='int')

array([1, 1, 1, 1, 1])

In [34]:
np.ones(5,dtype='bool')

array([ True,  True,  True,  True,  True])

#### 使用fill方法将数组设为指定值

In [35]:
a=np.array([1,2,3,4])

In [41]:
a.fill(5)
a

array([5, 5, 5, 5])

In [44]:
a.fill(2.5)
a

array([2, 2, 2, 2])

In [45]:
a=a.astype('float')
a.fill(2.5)
a

array([2.5, 2.5, 2.5, 2.5])

与列表不同，数组中要求所有元素的dtype是一样的，如果是不一样的，需要按照已有的类型进行转换

还可以使用一些特定的方法生成特殊的数组

#### 生成整数序列

In [48]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
a=np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

#### 生成等差数列 linspace 

In [ ]:
a=np.linspace(1,10,10)
a

从1到10（包含10），生成一共包含10个数的等差数列

In [55]:
a=np.linspace(1,10,15)
a

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

从1到10生成一共18个数的等差数列

#### 生成随机数np.random.rand()  0-1 随机数

In [56]:
np.random.rand(10)

array([4.72608628e-01, 3.92860461e-01, 9.11837445e-01, 7.20468385e-01,
       7.44984052e-05, 7.86560930e-01, 7.48370737e-01, 7.72417113e-01,
       3.48641652e-01, 4.27052757e-01])

#### 生成服从标准正态分布的随机数np.random.randn()

#### 生成随机整数np.random.rand(1,20,10)从1-20里面生成10个随机整数

In [59]:
np.random.randint(1,20,10)

array([14,  2, 16, 17,  9, 18,  3,  1, 10, 12])

In [5]:
np.random.randint(1,20,size=(2,10))

array([[ 7, 11,  5,  7, 17,  7, 13,  8,  2,  4],
       [ 9, 11,  9,  2, 17,  3,  5, 10,  8, 10]])

### 数组属性

#### 查看类型

In [5]:
type(a)

numpy.ndarray

查看数组中的数据类型

In [6]:
a.dtype

dtype('float64')

查看形状,会返回一个元组，每个元素代表这一维的元素数目

In [8]:
a.shape

(10,)

查看数组里面的元素数目

In [9]:
a.size

10

数组维度

In [10]:
a.ndim

1

## 索引和切片

和列表相似，数组也支持索引和切片操作

#### 索引第一个元素

In [12]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [13]:
a[0]

1

In [15]:
a[0]=10
a

array([10,  2,  3,  4])

切片，支持负索引

In [19]:
a=np.array([11,12,13,14,15])
a[1:3]

array([12, 13])

In [20]:
a[1:-2]

array([12, 13])

从第一个到倒数第二个

In [21]:
a[-4:3]

array([12, 13])

从倒数第四个到正数第四个

省略参数

In [23]:
a[-2:]

array([14, 15])

In [24]:
a[::2]

array([11, 13, 15])

## 多维数组及其属性

array还可以生成多维数组

In [29]:
a=np.array([[0,1,2,3],[10,11,12,13]])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [30]:
a.shape

(2, 4)

查看元素总个数

In [31]:
a.size

8

查看维度

In [33]:
a.ndim

2

### 多维数组索引

In [34]:
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

1是行索引，3是纵索引，中间用逗号隔开

In [37]:
a[1,3]

13

我们还可以使用单个索引来索引一整行内容

In [39]:
a[1]

array([10, 11, 12, 13])

In [41]:
a[:,1]

array([ 1, 11])

### 多为数组切片

多维数组也指出切片操作

In [42]:
a=np.array([[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25],[30,31,32,33,34,35],[40,41,42,43,44,45],[50,51,52,53,54,55]])
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

想要得到第一行的第4和第5两个元素

In [43]:
a[0,3:5]

array([3, 4])

最后两行的最后两列

In [44]:
a[-2:,-2:]

array([[44, 45],
       [54, 55]])

## 切片

切片在内存中使用的是引用机制

In [7]:
a=np.array([0,1,2,3,4])
a

array([0, 1, 2, 3, 4])

In [12]:
b=a[2:4]
b

array([2, 3])

In [13]:
print(b)

[2 3]


In [15]:
b[0]=10
a

array([ 0,  1, 10,  3,  4])

引用机制意味着python并没有给b分配新的空间来储存他的值，而是让b指向了a所分配的内存空间，因此，改变b会改变a的值：
而这种现象在列表中并不会出现

In [17]:
a=[1,2,3,4,5]
b=a[2:4]
b[0]=10
print(a)

[1, 2, 3, 4, 5]


这样做的好处是对于很大的数组，不用大量复制多余的值，节约了空间。缺点在于可能出现改变一个值而改变了另外一个值的情况

一个解决方法是使用copy（）方法产生一个复制，这个复制会申请新的内存

In [19]:
a=np.array([0,1,2,3,4])
b=a[2:4].copy()
b[0]=10
a

array([0, 1, 2, 3, 4])

### 花式索引

切片只能支持连续或者等间隔的切片操作，要想实现任意位置的操作。需要使用花式索引fancy slicing

#### 一维花式索引

##### 与range函数类似，我们可以使用arange函数来产生的等差数组

In [22]:
a=np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [24]:
index=[1,2,-3]
y=a[index]
print(y)

[10 20 70]


还可以使用布尔数组来花式索引=

In [30]:
mask=np.array([0,2,2,0,0,1,0,1,0,1],dtype=bool)
mask

array([False,  True,  True, False, False,  True, False,  True, False,
        True])

In [31]:
 a[mask]

array([10, 20, 50, 70, 90])

mask必须是布尔数组。长度必须和数组长度相等。

#### 二维数组 

In [34]:
a=np.array([[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25],[30,31,32,33,34,35],[40,41,42,43,44,45],[50,51,52,53,54,55]])
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

返回的是一条次对角线上的五个值

In [36]:
a[(0,1,2,3,4),(1,2,3,4,5)]

array([ 1, 12, 23, 34, 45])

返回最后三行的1,3,5列

In [37]:
a[(-3,-2,-1),(0,2,4)]

array([30, 42, 54])

也可以用mask进行索引 

In [38]:
mask=np.array([0,0,1,0,0,2],dtype=bool)
a[mask,2]

array([22, 52])

### 不完全索引


只给定行索引的时候，返回整行

In [39]:
y=a[:3]
y

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25]])

也可以使用花式索引去除第2,3,5行

In [40]:
con=np.array([0,1,1,0,1,0],dtype=bool)
a[con]

array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [40, 41, 42, 43, 44, 45]])

## where语句

where(array)

where函数会返回所有非零元素的索引

### 一维数组

In [2]:
a=np.array([0,12,5,20])

判断数组中的元素是不是大于10

In [3]:
a>10

array([False,  True, False,  True])

数组中所有大于10的元素的索引位置

In [4]:
np.where(a>10)

(array([1, 3], dtype=int64),)

### 类型转换

In [11]:
a=np.array([1.5,3],dtype=float)
a

array([1.5, 3. ])

#### asarray函数

In [9]:
a=np.array([1,2,3])
np.asarray(a,dtype=float)

array([1., 2., 3.])

#### astype方法

astype方法返回一个新数组

In [12]:
a=np.array([1,2,3])
a.astype(float)

array([1., 2., 3.])

In [13]:
a

array([1, 2, 3])

## 数组操作

### 我们以豆瓣10部高分电影为例

In [17]:
##电影名称
mv_name=['肖申克的救赎','控方证人','美丽人生','阿甘正传','霸王别姬','泰坦尼克号','辛德勒的名单','这个杀手不太冷','疯狂动物城','海豚湾']

In [18]:
##评分人数
mv_num=np.array([78965,32424,54345,56466,68757,56744,45675,36765,87686,34573,])

In [20]:
##评分
mv_score=np.array([9.6,9.3,9.3,9.2,9.7,9.4,9.6,9.3,9.2,9.2])

In [22]:
##电影时长（分钟）
mv_length=np.array([142,116,116,142,171,192,120,109,145.129])

### 数组排序

#### sort函数(按照从下到大排序，对数组本身没有变化

In [24]:
np.sort(mv_num)

array([32424, 34573, 36765, 45675, 54345, 56466, 56744, 68757, 78965,
       87686])

In [25]:
mv_num

array([78965, 32424, 54345, 56466, 68757, 56744, 45675, 36765, 87686,
       34573])

#### argsort

#### 返回从小到大的排列在数组中的索引位置

In [26]:
np.argsort(mv_num)

array([1, 9, 7, 6, 2, 3, 5, 4, 0, 8], dtype=int64)

In [27]:
order=np.argsort(mv_num)
order

array([1, 9, 7, 6, 2, 3, 5, 4, 0, 8], dtype=int64)

###  求和

In [28]:
np.sum(mv_num)

552400

In [29]:
mv_num.sum()

552400

### 最大值

In [30]:
np.max(mv_num)

87686

### 最小值

In [31]:
np.min(mv_length)

109.0

In [34]:
mv_length.min()

109.0

### 均值

## 数组变换

#### 数据重塑（reshape）、数据散开（ravel）和数据扁平化（flatten）

#### 横向合并hstack、纵向合并vstack，综合合并concatenate

#### 数组的分割hsplit vsplit split

#### 数据的转置transpose